version: 1.0.{build}

os: Visual Studio 2015
platform: Any CPU
configuration: Release
build:
  project: DotOPDS.sln
init:
  - ps: $env:GIT_HASH = $env:APPVEYOR_REPO_COMMIT.Substring(0, 7)
before_build:
  - ps: nuget restore

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-$(GIT_HASH)-$(APPVEYOR_REPO_BRANCH)'

shallow_clone: true
cache:
  - packages -> **\packages.config

test: off

artifacts:
  - path: 'DotOPDS\bin\Release\DotOPDS.exe'
    name: release_bin
